site_name: LOGos

theme:
  name: material
  language: en

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - content.code.copy

  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: light-blue
      accent: amber
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light-blue
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


plugins:
- search
- gen-files:
      scripts:
        - docs/gen_ref_pages.py
- literate-nav:
    nav_file: docs/SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        setup_commands:
            - import sys
            - sys.path.append("src")
        paths: [src]
        options:
            docstring_style: google
            docstring_options:
              show_if_no_docstring: true
            show_source: true
            members_order: "source"
            filters: [".*"]
            show_type_annotations: true

nav:
  - Home: index.md
  - Docs: 
    - "LOGos": reference/logos/logos.md
    - "Drain": reference/logos/drain.md
    - "TagUtils": reference/logos/tag_utils.md 
    - "CausalUnitSuggester": reference/logos/causal_unit_suggester.md
    - "AggregateSelector": reference/logos/aggregate_selector.md
    - "CausalDiscoverer": reference/logos/causal_discoverer.md
    - "EdgeStateMatrix": reference/logos/edge_state_matrix.md
    - "CandidateCauseRanker": reference/logos/candidate_cause_ranker.md
    - "Pruner": reference/logos/pruner.md
    - "Regression": reference/logos/regression.md
    - "GraphRenderer": reference/logos/graph_renderer.md
    - "ATECalculator": reference/logos/ate_calculator.md
    - "InteractiveCausalGraphRefiner": reference/logos/interactive_causal_graph_refiner.md
    - "ClusteringParams": reference/logos/clustering_params.md
    - "EdgeOccurrenceTree": reference/logos/edge_occurrence_tree.md
    - "Pickler": reference/logos/pickler.md
    - "Printer": reference/logos/printer.md
    - "Types": reference/logos/types.md
    - Variable Names: 
      - "ParsedVariableName": reference/logos/variable_name/parsed_variable_name.md
      - "PreparedVariableName": reference/logos/variable_name/prepared_variable_name.md
    - Aggregation/Imputation Functions: 
      - "Aggregation Functions": reference/logos/aggimp/agg_funcs.md
      - "Imputation Functions": reference/logos/aggimp/imp_funcs.md

  
markdown_extensions:
    - markdown_include.include:
        base_path: .
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - tables

